# 对话系统配置 - 基于原剧本扩展
# Dialogue System Configuration - Extended from Original Script

dialogue_system:
  # 学姐对话库（基于原剧本扩展）
  senpai_dialogues:
    encounter:
      dialogue_001:
        text: "你是新来的吧？画画过吗？"
        options:
          A:
            text: "其实我更擅长写代码，但我愿意试试画画。"
            affinity: +5
            personality: "谦逊+3, 开放+5"
            next: "senpai_dialogue_002"
          B:
            text: "画画？那种小孩子的东西我可没兴趣。"
            affinity: -3
            personality: "傲慢+5"
            next: "senpai_dialogue_negative"
            
      dialogue_002:
        text: "这幅画……构图还算不错，你是随便画的吗？"
        context: "你刚完成了一幅简单的素描"
        options:
          A:
            text: "嗯，我是随手画的，没想到能得到你的认可。"
            affinity: +3
            personality: "谦逊+5"
          B:
            text: "不，我可是很认真的！因为你在看嘛。"
            affinity: +8
            personality: "直率+5, 勇气+3"
            
    development:
      dialogue_003:
        text: "加入社团后，不能三天打鱼两天晒网。"
        options:
          A:
            text: "放心吧，我会认真对待。"
            affinity: +5
            personality: "责任感+5"
          B:
            text: "社团只是玩玩而已吧？不要太严肃了。"
            affinity: -5
            personality: "随性+3"
            
      dialogue_004:
        text: "我平时比较严格，你会不会觉得我很不好相处？"
        unlock_condition: "affinity >= 20"
        options:
          A:
            text: "严格才好啊，我喜欢有目标的人。"
            affinity: +8
            personality: "理解+5"
          B:
            text: "嗯……确实有点难相处。"
            affinity: -8
            personality: "直率+3"
            
      dialogue_005:
        text: "今天的社团活动结束了，你要不要和我一起收拾？"
        options:
          A:
            text: "当然可以，我来帮你。"
            affinity: +6
            personality: "体贴+5"
          B:
            text: "算了吧，我还有事要做。"
            affinity: -3
            personality: "独立+3"
            
    crisis:
      dialogue_006:
        text: "社团可能要解散了...我不知道该怎么办。"
        unlock_condition: "crisis_triggered"
        options:
          A:
            text: "别担心，我会想办法帮你的。"
            affinity: +15
            personality: "支持+10"
            flag: "help_crisis"
          B:
            text: "这种事情总会有解决办法的。"
            affinity: +5
            personality: "乐观+5"
          C:
            text: "也许这是个重新开始的机会。"
            affinity: +8
            personality: "积极+5"
            
    resolution:
      dialogue_007:
        text: "谢谢你为社团做的一切...你让我看到了艺术与技术结合的可能。"
        unlock_condition: "crisis_resolved"
        options:
          A:
            text: "和你在一起创作，我也学到了很多。"
            affinity: +10
            personality: "感恩+5"
          B:
            text: "这只是开始，我们还能创造更多可能。"
            affinity: +12
            personality: "远见+8"
            
  # 小白对话库（基于原剧本扩展）
  xiaobai_dialogues:
    encounter:
      dialogue_001:
        text: "Python 里的 for 循环，我总是写不对……"
        options:
          A:
            text: "来，我教你一个小技巧！"
            affinity: +8
            personality: "耐心+5, 乐于助人+5"
            next: "xiaobai_dialogue_002"
          B:
            text: "这种简单的东西，你都不会？"
            affinity: -10
            personality: "傲慢+5"
            next: "xiaobai_dialogue_negative"
            
      dialogue_002:
        text: "你看我借了好多书，会不会显得很傻？"
        options:
          A:
            text: "不会啊，这说明你很爱学习，很可爱。"
            affinity: +8
            personality: "鼓励+5, 真诚+5"
          B:
            text: "嗯……的确有点太贪心了。"
            affinity: -5
            personality: "直率+3"
            
    development:
      dialogue_003:
        text: "写代码的时候，我总喜欢喝奶茶……你呢？"
        options:
          A:
            text: "我也是！来，下次我请你一杯。"
            affinity: +10
            personality: "共同爱好+5, 主动+5"
          B:
            text: "我只喝水，健康第一。"
            affinity: +2
            personality: "自律+5"
            
      dialogue_004:
        text: "你会不会觉得我太依赖你了？"
        unlock_condition: "affinity >= 25"
        options:
          A:
            text: "依赖我也没关系，我喜欢这种感觉。"
            affinity: +12
            personality: "保护欲+8"
          B:
            text: "嗯……是有点吧。"
            affinity: -8
            personality: "独立+5"
            
      dialogue_005:
        text: "要不要一起留在图书馆自习？我想有人陪。"
        options:
          A:
            text: "好啊，我正好也要复习。"
            affinity: +8
            personality: "陪伴+5"
          B:
            text: "算了，我还是回宿舍打游戏吧。"
            affinity: -5
            personality: "娱乐优先+3"
            
    crisis:
      dialogue_006:
        text: "考试好难...如果考不好，就拿不到奖学金了。"
        unlock_condition: "crisis_triggered"
        options:
          A:
            text: "别担心，我陪你一起复习！"
            affinity: +20
            personality: "支持+15"
            flag: "help_study"
          B:
            text: "相信自己，你一定可以的！"
            affinity: +8
            personality: "鼓励+8"
          C:
            text: "奖学金不是最重要的。"
            affinity: +3
            personality: "豁达+5"
            
    resolution:
      dialogue_007:
        text: "谢谢你一直陪着我...没有你，我永远不可能做到这些。"
        unlock_condition: "crisis_resolved"
        options:
          A:
            text: "看到你成长，我也很开心。"
            affinity: +12
            personality: "成就感+8"
          B:
            text: "这是你自己努力的结果。"
            affinity: +10
            personality: "谦逊+8"
            
  # 姐姐对话库（基于原剧本扩展）
  jiejie_dialogues:
    encounter:
      dialogue_001:
        text: "你也喜欢在咖啡店看书吗？"
        options:
          A:
            text: "是啊，这里很安静，很适合思考。"
            affinity: +8
            personality: "深度+5, 思考+5"
            next: "jiejie_dialogue_002"
          B:
            text: "其实我只是随便找个地方坐。"
            affinity: +2
            personality: "随性+3"
            
      dialogue_002:
        text: "研究生的生活，其实没有你想象的那么光鲜。"
        options:
          A:
            text: "我能理解，压力一定很大吧。"
            affinity: +8
            personality: "理解+8, 同理心+5"
          B:
            text: "那我还是不要考研了。"
            affinity: -3
            personality: "逃避+3"
            
    development:
      dialogue_003:
        text: "你觉得，什么样的人最值得依靠？"
        options:
          A:
            text: "稳重冷静的人。"
            affinity: +10
            personality: "成熟+8"
          B:
            text: "长得好看的人。"
            affinity: -5
            personality: "肤浅+5"
            
      dialogue_004:
        text: "我常常一个人坐到很晚，你不会觉得孤单吗？"
        unlock_condition: "affinity >= 20"
        options:
          A:
            text: "有时候孤单是种享受。"
            affinity: +8
            personality: "独立+5, 深度+5"
          B:
            text: "一个人太寂寞了，我受不了。"
            affinity: +3
            personality: "社交需求+5"
            
      dialogue_005:
        text: "如果有一天，我遇到困难，你会帮我吗？"
        options:
          A:
            text: "当然会，你不用一个人扛着。"
            affinity: +12
            personality: "支持+10"
          B:
            text: "我大概帮不了你吧。"
            affinity: -8
            personality: "自卑+5"
            
    crisis:
      dialogue_006:
        text: "我的研究被否决了...半年的努力白费了。"
        unlock_condition: "crisis_triggered"
        options:
          A:
            text: "这不是终点，而是新的开始。"
            affinity: +15
            personality: "智慧+10, 支持+10"
            flag: "emotional_support"
          B:
            text: "我们一起分析问题，找到解决方案。"
            affinity: +18
            personality: "实际+10, 合作+10"
            flag: "practical_help"
          C:
            text: "你需要休息一下，重新整理思路。"
            affinity: +8
            personality: "关心+8"
            
    resolution:
      dialogue_007:
        text: "和你在一起的时光，是我研究生涯中最珍贵的回忆。"
        unlock_condition: "crisis_resolved"
        options:
          A:
            text: "我们的相遇改变了彼此。"
            affinity: +15
            personality: "深情+10"
          B:
            text: "这段经历让我们都成长了。"
            affinity: +12
            personality: "成熟+8"

# 通用对话触发条件
dialogue_triggers:
  time_based:
    morning: "早上好感度对话"
    afternoon: "下午学习对话"
    evening: "晚上深度对话"
    night: "深夜谈心对话"
    
  affinity_based:
    low: "0-30好感度对话"
    medium: "31-60好感度对话" 
    high: "61-85好感度对话"
    romance: "86-100好感度对话"
    
  event_based:
    first_meeting: "初次见面对话"
    daily_interaction: "日常互动对话"
    crisis_moment: "危机时刻对话"
    resolution: "问题解决对话"
    confession: "告白相关对话"

# 对话效果系统
dialogue_effects:
  affinity_modifiers:
    excellent_choice: "+15到+20"
    good_choice: "+8到+12"
    neutral_choice: "+3到+5"
    poor_choice: "-3到-8"
    terrible_choice: "-10到-15"
    
  personality_development:
    traits:
      - "谦逊"
      - "自信"
      - "耐心"
      - "体贴"
      - "智慧"
      - "勇气"
      - "理解"
      - "支持"
      - "深度"
      - "成熟"
      
  special_flags:
    crisis_helper: "在危机中提供帮助"
    emotional_support: "提供情感支持"
    practical_helper: "提供实际帮助"
    deep_connection: "建立深度连接"
    future_planning: "共同规划未来"

# 对话系统规则
dialogue_rules:
  selection_method: "数字键选择 (1/2/3/4)"
  timeout: 30  # 30秒选择时间
  default_choice: 1  # 超时默认选择
  
  display_format:
    show_affinity: false  # 对话中不显示好感度变化
    show_personality: false  # 对话中不显示性格变化
    show_effects_after: true  # 对话后显示效果
    
  availability:
    repeatable: false  # 大部分对话不可重复
    special_repeatable:  # 特殊可重复对话
      - "daily_greeting"
      - "study_together"
      - "casual_chat"
