# 姐姐路线剧情帧 - 成熟的智慧之恋
# Jiejie Route Story Frames - Mature Wisdom Romance

jiejie_route:
  # 邂逅阶段
  encounter_jiejie_001:
    type: "narrative"
    category: "encounter"
    title: "校外探索"
    scene: "校门口"
    
    content: |
      【场景：校门口，傍晚时分】
      
      经过了开学典礼的忙碌，你决定到校外转转，
      熟悉一下周边的环境。
      
      走出校门，你看到了一条热闹的商业街。
      各种小店、餐厅、咖啡厅林立两旁。
      
      【夕阳西下，街道上人来人往】
      
      "大学生活不应该只局限在校园内，
      了解这座城市也是很重要的。"
      
      你这样想着，漫步在陌生的街道上。
      
      【空气中飘着咖啡的香味】
      
      不远处，一家装修雅致的咖啡厅吸引了你的注意。
      暖黄色的灯光从窗户透出，
      给人一种温馨而宁静的感觉。
      
    audio:
      background_music: "evening_city.mp3"
      sound_effects: ["footsteps", "distant_traffic", "cafe_ambience"]
      
    transitions:
      next: "encounter_jiejie_002"
      
  encounter_jiejie_002:
    type: "narrative"
    category: "encounter"
    title: "温馨咖啡厅"
    scene: "『时光』咖啡厅门前"
    
    content: |
      【场景：『时光』咖啡厅门前】
      
      你走近这家名为『时光』的咖啡厅。
      
      透过玻璃窗，你看到里面的装修很有文艺气息：
      木质的桌椅、暖色的灯光、墙上挂着各种文艺作品。
      
      【几位顾客安静地坐着，有的在看书，有的在工作】
      
      这种安静的环境很适合思考和放松。
      
      "进去坐坐吧，正好也有些累了。"
      
      【推开咖啡厅的门，清脆的铃声响起】
      
      "欢迎光临！"服务员热情地打招呼。
      
      你选择了一个靠窗的位置坐下，
      点了一杯美式咖啡，准备享受这个安静的黄昏。
      
    scene_atmosphere:
      lighting: "暖黄色灯光"
      ambience: "安静文艺"
      mood: "放松舒适"
      
    transitions:
      next: "encounter_jiejie_003"
      
  encounter_jiejie_003:
    type: "narrative"
    category: "encounter"
    title: "知性的身影"
    scene: "『时光』咖啡厅内"
    
    content: |
      【场景：咖啡厅内，你的座位】
      
      坐下后，你环顾了一下四周。
      
      就在你斜对面的角落位置，
      坐着一位气质优雅的女性。
      
      【她就是温心，披肩长发，穿着简约的风衣】
      
      她正专注地阅读着一本厚厚的学术书籍，
      偶尔会在笔记本上记录什么。
      
      桌上放着一杯已经凉了的咖啡，
      显然她已经在这里待了很久。
      
      【她的侧脸在灯光下显得特别温柔】
      
      从她的气质和阅读的书籍来看，
      应该是一位研究生学姐。
      
      【这时，她似乎遇到了什么问题】
      
      你看到她皱起了眉头，
      在思考着什么复杂的问题。
      
    character_introduction:
      name: "温心"
      first_impression: "知性、优雅、专注学术的成熟女性"
      current_activity: "在咖啡厅阅读学术资料"
      
    transitions:
      next: "encounter_jiejie_004"
      
  encounter_jiejie_004:
    type: "choice"
    category: "encounter"
    title: "是否交流"
    scene: "『时光』咖啡厅内"
    
    content: |
      你一边喝着咖啡，一边观察着这位知性的学姐。
      
      她时而翻阅资料，时而在笔记本上写写画画，
      偶尔还会轻叹一声，似乎遇到了什么困难。
      
      作为新生的你，对这种学术氛围很感兴趣，
      也许可以和她交流一下？
      
    choices:
      choice_a:
        text: "主动过去询问是否需要帮助"
        effect:
          personality: "主动热心+5"
          jiejie_affinity: "+2"
        next_frame: "encounter_jiejie_005_help"
        
      choice_b:
        text: "安静观察，等待合适的机会"
        effect:
          personality: "观察力+3"
          jiejie_affinity: "+3"
        next_frame: "encounter_jiejie_005_wait"
        
      choice_c:
        text: "专心享受自己的咖啡时光"
        effect:
          personality: "独立+3"
          jiejie_affinity: "+1"
        next_frame: "encounter_jiejie_005_focus"
        
      choice_d:
        text: "结账离开，不打扰她"
        effect:
          personality: "体贴+5"
        next_frame: "rest_frame_001"
        
  encounter_jiejie_005_wait:
    type: "narrative"
    category: "encounter"
    title: "意外的邂逅"
    scene: "『时光』咖啡厅内"
    
    content: |
      【你决定安静地等待合适的时机】
      
      一边品味着咖啡，一边欣赏着窗外的夜景。
      
      【时间慢慢过去】
      
      大概半小时后，那位学姐终于放下了手中的笔，
      轻轻地伸了个懒腰。
      
      【她注意到了你的目光】
      
      四目相对，她微微一笑，点头致意。
      
      【她起身去前台续杯咖啡】
      
      经过你的桌子时，她停下了脚步。
      
      温心："同学，你好。我注意到你已经坐了很久了，
      也在看书吗？"
      
      她的声音很温柔，带着一种成熟女性特有的知性魅力。
      
      【她注意到你桌上放着的编程书籍】
      
      "计算机专业的？我是研究生院的温心。"
      
    character_stats:
      jiejie_affinity: 8
      first_impression: "有耐心、不急躁的新生"
      
    transitions:
      next: "encounter_jiejie_006"
      
  encounter_jiejie_005_help:
    type: "dialogue"
    category: "encounter"
    title: "主动交流"
    scene: "『时光』咖啡厅内"
    
    content: |
      【你端着咖啡走向她的桌子】
      
      "不好意思，我看你好像遇到了什么困难，
      需要帮忙吗？"
      
      【温心抬起头，略带惊讶地看着你】
      
      温心："你好，谢谢你的关心。
      我在研究一个数据分析的问题，有些复杂。"
      
      她指着桌上的资料。
      
      "你是...？"
      
      "我是{主角名字}，刚入学的新生。
      如果是数据分析相关的，也许我能帮上忙。"
      
      温心："新生？你就是昨天开学典礼上的新生代表吧？
      没想到能在这里遇到。"
      
      【她的眼中闪过一丝兴趣】
      
      "如果你不介意的话，可以坐下聊聊。"
      
    character_stats:
      jiejie_affinity: 6
      first_impression: "主动热心的优秀新生"
      
    transitions:
      next: "encounter_jiejie_006"
      
  encounter_jiejie_006:
    type: "dialogue"
    category: "encounter"
    title: "深度交流"
    scene: "『时光』咖啡厅内"
    
    content: |
      【你坐在温心对面】
      
      温心："我正在研究社交网络中的用户行为模式，
      需要处理大量的数据，但传统的方法效率太低。"
      
      "你有什么想法吗？"
      
      【你看了看她的资料】
      
      "这种问题可以用机器学习的方法来解决。
      我可以写个程序来协助数据处理。"
      
      温心："真的吗？你才大一就会机器学习？"
      
      她显然对你的能力感到惊讶。
      
      "看来这次开学典礼选的新生代表确实不简单。"
      
      【她的语气中带着赞赏】
      
      "不过，学术研究不只是技术问题，
      还需要对人性和社会的深度理解。"
      
    character_development:
      jiejie_affinity: 15
      academic_discussion: true
      intellectual_connection: "技术与人文的碰撞"
      
    dialogue_options:
      option_a:
        text: "您说得对，技术只是工具，理解才是关键"
        jiejie_affinity: "+8"
        wisdom: "+5"
        next_frame: "development_jiejie_001"
        
      option_b:
        text: "我很想学习您的研究方法和思路"
        jiejie_affinity: "+6"
        humility: "+3"
        next_frame: "development_jiejie_001"
        
      option_c:
        text: "也许我们可以合作，技术与人文结合"
        jiejie_affinity: "+5"
        collaboration: "+5"
        next_frame: "development_jiejie_001"
        
    transitions:
      next: "development_jiejie_001"
      
  # 发展阶段
  development_jiejie_001:
    type: "narrative"
    category: "development"
    title: "咖啡厅常客"
    scene: "『时光』咖啡厅"
    
    content: |
      【场景：一周后的『时光』咖啡厅】
      
      自从那次邂逅后，你开始经常来这家咖啡厅。
      
      温心似乎也是这里的常客，
      你们经常在同一时间段遇到。
      
      【你们已经建立了一种默契】
      
      各自做着自己的事情，
      但偶尔会交流一些学术或人生的话题。
      
      【今天，温心看起来有些疲惫】
      
      "研究生的生活比想象中要累啊。"
      她轻叹一声。
      
      "导师的要求很高，实验数据总是不理想，
      论文的进展也很缓慢。"
      
      【她看向窗外】
      
      "有时候会怀疑自己选择这条路是否正确。"
      
    character_development:
      jiejie_affinity: 25
      relationship_stage: "咖啡厅朋友"
      vulnerability_shown: "学术压力的困扰"
      
    transitions:
      next: "development_jiejie_002"
      
  development_jiejie_002:
    type: "choice"
    category: "development"
    title: "如何回应"
    scene: "『时光』咖啡厅"
    
    content: |
      看到温心的困扰，你想要给她一些支持。
      
      作为一个新生，你虽然没有研究生的经历，
      但也许能从不同的角度给她一些启发？
      
    choices:
      choice_a:
        text: "分享自己克服困难的经历和方法"
        effect:
          jiejie_affinity: "+8"
          emotional_support: "+10"
        next_frame: "development_jiejie_003_experience"
        
      choice_b:
        text: "用技术手段帮她提高研究效率"
        effect:
          jiejie_affinity: "+6"
          practical_help: "+15"
        next_frame: "development_jiejie_003_technical"
        
      choice_c:
        text: "倾听她的困扰，给予情感支持"
        effect:
          jiejie_affinity: "+10"
          emotional_bond: "+15"
        next_frame: "development_jiejie_003_listen"
        
      choice_d:
        text: "建议她换个环境放松一下"
        effect:
          jiejie_affinity: "+4"
          care: "+8"
        next_frame: "development_jiejie_003_relax"
        
  development_jiejie_003_listen:
    type: "dialogue"
    category: "development"
    title: "倾听与陪伴"
    scene: "『时光』咖啡厅"
    
    content: |
      【你放下手中的书，专注地看着她】
      
      "想聊聊具体是什么问题吗？
      也许说出来会好一些。"
      
      温心看着你真诚的眼神，似乎被触动了。
      
      温心："其实...我有时候觉得很孤独。
      研究生的生活很单调，每天都是实验室、图书馆、宿舍三点一线。"
      
      "身边的同学都忙着自己的研究，
      很少有时间进行深入的交流。"
      
      【她的声音有些低沉】
      
      "我选择读研是因为喜欢学术研究，
      但没想到会这么孤独。"
      
      【你静静地听着，不时点头表示理解】
      
      "谢谢你愿意听我说这些。
      和你聊天，我感觉轻松了很多。"
      
    character_development:
      jiejie_affinity: 35
      emotional_bond: +20
      trust_level: "开始信任"
      loneliness_revealed: true
      
    transitions:
      next: "development_jiejie_004"
      
  development_jiejie_004:
    type: "narrative"
    category: "development"
    title: "定期相约"
    scene: "『时光』咖啡厅"
    
    content: |
      【场景：几天后的傍晚】
      
      从那次深谈后，你们的关系更进了一步。
      
      温心："你知道吗？我已经把每天傍晚的这个时间
      当作一天中最期待的时光了。"
      
      【她的笑容比以前更加自然】
      
      "和你聊天让我想起了刚入学时的那种纯真和热情。"
      
      你们开始分享更多的话题：
      学术理想、人生规划、兴趣爱好...
      
      【你发现温心不仅有学术上的深度，也有生活中的情趣】
      
      "你有没有想过，等毕业后想做什么？"
      她问你。
      
      【这种关于未来的讨论让你们的关系更加深入】
      
    character_development:
      jiejie_affinity: 45
      daily_routine: "每天傍晚的咖啡时光"
      future_planning: "开始讨论人生规划"
      
    transitions:
      next: "development_jiejie_005"
      
  # 危机阶段
  crisis_jiejie_001:
    type: "narrative"
    category: "crisis"
    title: "学术挫折"
    scene: "『时光』咖啡厅"
    
    content: |
      【场景：某个雨夜的咖啡厅】
      
      今天的温心看起来格外沮丧。
      
      她坐在老位置上，但没有打开任何书籍，
      只是呆呆地看着窗外的雨。
      
      【你走过去坐下】
      
      "出什么事了吗？"
      
      温心："我的研究项目...被导师否决了。"
      
      她的声音很平静，但你能感受到其中的痛苦。
      
      "我花了半年时间的研究成果，
      导师说没有创新性，要求我重新开始。"
      
      【她看着桌面】
      
      "更糟糕的是，我看到其他同学都进展顺利，
      开始准备发表论文了。
      而我...好像永远在原地踏步。"
      
    character_development:
      jiejie_affinity: 50
      crisis_point: "学术研究受挫"
      emotional_vulnerability: "完全暴露"
      need_support: true
      
    transitions:
      next: "crisis_jiejie_002"
      
  crisis_jiejie_002:
    type: "choice"
    category: "crisis"
    title: "关键的支持"
    scene: "『时光』咖啡厅"
    
    content: |
      看到温心如此沮丧，你的心中涌起强烈的保护欲。
      
      这是你第一次看到平时坚强的她如此脆弱，
      你知道这个时候的支持对她来说非常重要。
      
    choices:
      choice_a:
        text: "陪她分析研究方向，提供技术支持"
        effect:
          jiejie_affinity: "+15"
          practical_help: "+20"
          problem_solving: "+10"
        next_frame: "crisis_jiejie_003_analysis"
        
      choice_b:
        text: "给她情感支持，坚定她的信心"
        effect:
          jiejie_affinity: "+12"
          emotional_support: "+25"
          confidence: "+15"
        next_frame: "crisis_jiejie_003_emotional"
        
      choice_c:
        text: "建议她暂时放下研究，好好休息"
        effect:
          jiejie_affinity: "+8"
          care: "+15"
        next_frame: "crisis_jiejie_003_rest"
        
      choice_d:
        text: "分享自己的失败经历，让她知道她不孤单"
        effect:
          jiejie_affinity: "+10"
          empathy: "+20"
          emotional_bond: "+15"
        next_frame: "crisis_jiejie_003_share"
        
  crisis_jiejie_003_emotional:
    type: "dialogue"
    category: "crisis"
    title: "坚定的支持"
    scene: "『时光』咖啡厅"
    
    content: |
      【你握住她的手】
      
      "温心，听我说。"
      
      【她抬起头，眼中含着泪水】
      
      "我知道现在很痛苦，但这不代表你的研究没有价值。
      学术研究本来就是一个充满挫折的过程。"
      
      "更重要的是，我看到了你对学术的纯真热爱，
      这种热爱不应该被一次挫折所击败。"
      
      【温心的眼神逐渐坚定起来】
      
      "你还记得你跟我说过的话吗？
      '理解人性是最复杂但也最有意义的研究'。"
      
      "这句话深深地触动了我，
      一个能说出这样话的人，怎么可能没有创新的能力？"
      
      【她紧紧握住你的手】
      
      温心："谢谢你...在我最需要的时候支持我。"
      
    character_development:
      jiejie_affinity: 62
      emotional_breakthrough: true
      trust_deepened: "完全信任"
      support_recognized: "深度感激"
      
    transitions:
      next: "resolution_jiejie_001"
      
  # 解决阶段
  resolution_jiejie_001:
    type: "narrative"
    category: "resolution"
    title: "重新开始"
    scene: "大学图书馆研究室"
    
    content: |
      【场景：一个月后，大学图书馆的研究室】
      
      经过那次深谈后，温心重新燃起了研究的热情。
      
      更让人惊讶的是，她邀请你作为技术顾问，
      共同参与她的新研究项目。
      
      【你们坐在研究室里，面前摊满了资料】
      
      温心："这次我想尝试一个全新的角度——
      用人工智能技术来分析社交行为背后的心理动机。"
      
      "技术和人文的结合，就像我们的友谊一样。"
      
      【她看着你，眼中充满了信任和感激】
      
      经过几周的合作，你们的研究取得了突破性进展。
      导师对新的研究方向非常满意，
      甚至建议她申请研究生创新基金。
      
    character_development:
      jiejie_affinity: 75
      collaboration: "深度学术合作"
      achievement: "研究突破"
      recognition: "导师认可"
      
    transitions:
      next: "resolution_jiejie_002"
      
  resolution_jiejie_002:
    type: "dialogue"
    category: "resolution"
    title: "深深的感激"
    scene: "『时光』咖啡厅"
    
    content: |
      【场景：熟悉的『时光』咖啡厅，庆祝研究突破】
      
      温心："如果没有你，我可能已经放弃了。"
      
      她举起咖啡杯，眼中闪闪发光。
      
      "你不仅帮我解决了技术问题，
      更重要的是给了我继续下去的勇气。"
      
      【她停顿了一下】
      
      "我开始明白，人生中最珍贵的不是学术成就，
      而是能够找到真正理解和支持自己的人。"
      
      【她看着你的眼睛】
      
      "你知道吗？和你在一起的这段时间，
      是我研究生生涯中最快乐的时光。"
      
      "我想...这已经超越了一般的友谊。"
      
    character_development:
      jiejie_affinity: 85
      emotional_confession: "暗示特殊感情"
      life_philosophy: "重新定义人生价值"
      
    dialogue_options:
      option_a:
        text: "我也有同样的感觉，你对我很特别"
        jiejie_affinity: "+15"
        romance_flag: true
        
      option_b:
        text: "能帮到你，我也很快乐"
        jiejie_affinity: "+8"
        
      option_c:
        text: "这种互相支持的感觉很珍贵"
        jiejie_affinity: "+12"
        wisdom: "+5"
        
    transitions:
      next: "resolution_jiejie_003"
      
  # 结局准备
  pre_ending_jiejie_001:
    type: "narrative"
    category: "resolution"
    title: "未来的约定"
    scene: "大学屋顶花园"
    
    content: |
      【场景：学期末，大学屋顶花园，星空璀璨】
      
      温心的研究项目获得了学院的最高奖项，
      她也收到了国外知名大学的博士邀请。
      
      【你们站在屋顶花园，俯瞰城市夜景】
      
      温心："还记得我们第一次在咖啡厅相遇吗？"
      
      "那时候的我迷茫、孤独，对未来充满不确定。"
      
      【她转身面对你】
      
      "是你让我重新找到了方向，
      不仅是学术上的，更是人生的。"
      
      "我想...我想告诉你一些话。"
      
      【她的声音有些颤抖，但眼神坚定】
      
      "这段时间以来，你已经成为我生命中最重要的人。"
      
    character_development:
      jiejie_affinity: 95
      achievement_shared: "共同的成功"
      future_planning: "面临重要选择"
      emotional_climax: "告白前夕"
      
    transitions:
      condition: "if affinity >= 100"
      success: "ending_jiejie_true"
      failure: "ending_jiejie_good"
      
  # 真结局触发条件检查
  affinity_check_jiejie:
    type: "system"
    category: "resolution"
    
    conditions:
      true_ending:
        jiejie_affinity: ">=100"
        emotional_support_given: true
        crisis_helped: true
        collaboration_success: true
        
      good_ending:
        jiejie_affinity: ">=80"
        emotional_support_given: true
        
      normal_ending:
        jiejie_affinity: ">=60"
        
      friend_ending:
        jiejie_affinity: "<60"
        
    transitions:
      true_ending: "ending_jiejie_true"
      good_ending: "ending_jiejie_good" 
      normal_ending: "ending_jiejie_normal"
      friend_ending: "ending_jiejie_friend"
