# 小白路线剧情帧 - 纯真的编程之恋
# Xiaobai Route Story Frames - Pure Programming Romance

xiaobai_route:
  # 邂逅阶段
  encounter_xiaobai_001:
    type: "narrative"
    category: "encounter"
    title: "图书馆探索"
    scene: "图书馆大厅"
    
    content: |
      【场景：图书馆大厅，下午时光】
      
      你决定去图书馆熟悉一下学习环境。
      
      图书馆很大，分为好几层：
      一楼是期刊阅览区，二楼是人文社科，
      三楼是理工科书籍，四楼是电子阅览室。
      
      【你拿着借书卡，准备办理相关手续】
      
      "既然来了，就找几本编程相关的书看看吧。"
      
      你乘电梯来到三楼的理工科区域。
      这里相对安静，只有偶尔翻书页和敲击键盘的声音。
      
      【走过一排排书架】
      
      计算机科学区域在图书馆的最深处，
      那里通常是最安静的地方。
      
    audio:
      background_music: "quiet_library.mp3"
      sound_effects: ["footsteps", "distant_page_turning", "keyboard_typing"]
      
    transitions:
      next: "encounter_xiaobai_002"
      
  encounter_xiaobai_002:
    type: "narrative"
    category: "encounter"
    title: "困惑的身影"
    scene: "图书馆计算机科学区"
    
    content: |
      【场景：计算机科学书架区域】
      
      当你走近计算机科学区域时，
      发现有一个娇小的身影坐在靠窗的位置。
      
      【她就是雪梨，白色短发，戴着大号耳机】
      
      她面前摊开着一本厚厚的《Python程序设计基础》，
      旁边还有几本算法和数据结构的书籍。
      
      【你注意到她的表情】
      
      她时而皱眉思考，时而在笔记本上写写画画，
      偶尔还会轻声嘀咕什么。
      
      从她的表情可以看出，她遇到了什么难题。
      
      【她突然有些沮丧地趴在了桌子上】
      
      "呜呜...这个循环到底怎么写呀..."
      她的声音很小，但你刚好听到了。
      
    character_introduction:
      name: "雪梨"
      first_impression: "努力学习但遇到困难的可爱女孩"
      current_state: "为编程问题困扰"
      
    transitions:
      next: "encounter_xiaobai_003"
      
  encounter_xiaobai_003:
    type: "choice"
    category: "encounter"
    title: "是否帮助"
    scene: "图书馆计算机科学区"
    
    content: |
      看到这个白发女孩为编程问题苦恼，
      作为编程高手的你，内心涌起了想要帮助她的冲动。
      
      但是贸然过去可能会吓到她，
      毕竟你们还不认识...
      
    choices:
      choice_a:
        text: "主动走过去询问是否需要帮助"
        effect:
          personality: "热心助人+5"
          xiaobai_affinity: "+3"
        next_frame: "encounter_xiaobai_004_help"
        
      choice_b:
        text: "先在附近选书，等待合适的时机"
        effect:
          personality: "谨慎观察+3"
          xiaobai_affinity: "+2"
        next_frame: "encounter_xiaobai_004_wait"
        
      choice_c:
        text: "假装路过，看看她遇到了什么问题"
        effect:
          personality: "间接关心+2"
          xiaobai_affinity: "+1"
        next_frame: "encounter_xiaobai_004_observe"
        
      choice_d:
        text: "不打扰她，去其他区域看书"
        effect:
          personality: "尊重他人+3"
        next_frame: "encounter_jiejie_001"
        
  encounter_xiaobai_004_help:
    type: "dialogue"
    category: "encounter"
    title: "主动援助"
    scene: "图书馆计算机科学区"
    
    content: |
      【你走向她的座位】
      
      "同学，你好。我看你好像遇到了编程问题，需要帮助吗？"
      
      【雪梨抬起头，有些惊讶地看着你】
      
      雪梨："啊！你...你是昨天开学典礼上的新生代表！"
      
      她的眼睛瞬间亮了起来，就像看到了救星一样。
      
      雪梨："真的可以吗？我在写一个for循环，但总是出错..."
      
      【她指着屏幕上的代码】
      
      你看了一眼，立刻发现了问题所在——
      是一个很常见的缩进错误。
      
      "这里的缩进有问题。Python对缩进很敏感，
      循环体内的代码需要保持一致的缩进。"
      
    character_stats:
      xiaobai_affinity: 8
      first_impression: "编程大神主动帮忙！"
      
    transitions:
      next: "encounter_xiaobai_005"
      
  encounter_xiaobai_004_wait:
    type: "narrative"
    category: "encounter"
    title: "等待时机"
    scene: "图书馆计算机科学区"
    
    content: |
      【你在附近的书架前假装选书】
      
      你拿起一本《算法导论》，偶尔瞄向那个白发女孩。
      
      她似乎越来越沮丧，甚至开始轻声抱怨：
      "为什么别人都觉得编程很简单呀..."
      
      【这时，她无意中朝你这边看了一眼】
      
      四目相对，她似乎有些不好意思，
      连忙低下头继续看书。
      
      【你觉得时机到了】
      
      "同学，我看你在学Python？"
      你拿着手中的算法书走了过去。
      
      雪梨："嗯...但是好难啊。你也是学计算机的吗？"
      
    character_stats:
      xiaobai_affinity: 6
      first_impression: "很有耐心的学长"
      
    transitions:
      next: "encounter_xiaobai_005"
      
  encounter_xiaobai_004_observe:
    type: "narrative"
    category: "encounter"
    title: "默默关注"
    scene: "图书馆计算机科学区"
    
    content: |
      【你假装在书架间浏览，实际上在观察她的困难】
      
      从她的屏幕反光中，你看到了她的代码。
      是一个简单的for循环练习，但有几个小错误。
      
      【她继续尝试了几分钟，越来越困扰】
      
      "唔...这样也不对..."
      她轻声嘀咕着，有些想要放弃的样子。
      
      【就在这时，她的水杯不小心碰倒了】
      
      "啊！"她惊呼一声，慌忙去擦桌上的水。
      
      【这是个帮忙的好机会】
      
      你连忙走过去递给她纸巾：
      "没事吧？"
      
      雪梨："谢谢！真是太不好意思了..."
      
    character_stats:
      xiaobai_affinity: 5
      first_impression: "善良的好心人"
      
    transitions:
      next: "encounter_xiaobai_005"
      
  encounter_xiaobai_005:
    type: "dialogue"
    category: "encounter"
    title: "编程指导"
    scene: "图书馆计算机科学区"
    
    content: |
      【你坐在她旁边，看着她的代码】
      
      "我可以看看你的代码吗？也许能帮你找找问题。"
      
      雪梨："真的吗？太好了！我叫雪梨，是计算机专业的新生。"
      
      "我是{主角名字}。来看看这个循环..."
      
      【你指着屏幕上的代码】
      
      "这里有几个小问题。首先，缩进要保持一致；
      然后，这个变量名拼写错了；
      最后，循环条件可以简化一下。"
      
      雪梨："哇！你好厉害！一下子就看出这么多问题！"
      
      她的眼中满是崇拜和感激。
      
      【你耐心地为她解释每一个错误】
      
      "其实这些都是很常见的新手错误，多练习就好了。"
      
    character_development:
      xiaobai_affinity: 15
      relationship_stage: "学习指导者"
      teaching_moment: true
      
    dialogue_options:
      option_a:
        text: "如果以后还有问题，可以随时问我"
        xiaobai_affinity: "+5"
        personality: "乐于助人+5"
        next_frame: "development_xiaobai_001"
        
      option_b:
        text: "编程需要大量练习，你要加油哦"
        xiaobai_affinity: "+3"
        personality: "鼓励他人+3"
        next_frame: "development_xiaobai_001"
        
      option_c:
        text: "我可以推荐几本好的入门书给你"
        xiaobai_affinity: "+4"
        personality: "分享知识+3"
        next_frame: "development_xiaobai_001"
        
    transitions:
      next: "development_xiaobai_001"
      
  # 发展阶段
  development_xiaobai_001:
    type: "narrative"
    category: "development"
    title: "学习伙伴"
    scene: "图书馆自习区"
    
    content: |
      【场景：一周后的图书馆自习区】
      
      自从上次帮助雪梨解决编程问题后，
      你们约定每天晚上在图书馆一起学习。
      
      【你们固定坐在靠窗的位置】
      
      雪梨总是会准备两杯奶茶，
      一杯给自己，一杯给你。
      
      "学长，这个递归函数我还是不太懂..."
      她指着教材上的例子。
      
      【你放下自己的书，耐心地为她解释】
      
      "递归就像是俄罗斯套娃，一层套一层。
      我们来画个图理解一下..."
      
      【你在草稿纸上画着示意图】
      
      雪梨："哦！这样看就清楚多了！
      学长你解释得比老师还要好懂！"
      
      她开心地笑着，眼睛弯成了月牙形。
      
    character_development:
      xiaobai_affinity: 25
      daily_routine: "图书馆学习"
      gift_habit: "每天的奶茶"
      
    transitions:
      next: "development_xiaobai_002"
      
  development_xiaobai_002:
    type: "choice"
    category: "development"
    title: "学习方式"
    scene: "图书馆自习区"
    
    content: |
      经过几天的观察，你发现雪梨的学习方式不太高效。
      她总是试图死记硬背代码，而不是理解背后的逻辑。
      
      今天她又在为一道练习题苦恼。
      
      雪梨："学长，这道题我看了好久都不会做..."
      
      你该如何帮助她？
      
    choices:
      choice_a:
        text: "直接告诉她答案，让她先有成就感"
        effect:
          xiaobai_affinity: "+3"
          xiaobai_dependency: "+5"
        next_frame: "development_xiaobai_003_answer"
        
      choice_b:
        text: "引导她自己思考，培养解题思路"
        effect:
          xiaobai_affinity: "+8"
          xiaobai_growth: "+10"
          teaching_skill: "+5"
        next_frame: "development_xiaobai_003_guide"
        
      choice_c:
        text: "和她一起分析，共同解决问题"
        effect:
          xiaobai_affinity: "+6"
          partnership: "+5"
        next_frame: "development_xiaobai_003_together"
        
  development_xiaobai_003_guide:
    type: "dialogue"
    category: "development"
    title: "启发式教学"
    scene: "图书馆自习区"
    
    content: |
      【你没有直接给出答案，而是开始提问】
      
      "雪梨，我们先不看代码，你能告诉我这道题想要解决什么问题吗？"
      
      雪梨："嗯...是要找出数组中的最大值。"
      
      "很好！那你觉得，如果让你手工来找，你会怎么做？"
      
      雪梨："我会...一个个看，然后记住最大的那个？"
      
      "没错！编程其实就是把这个思路翻译成计算机能理解的语言。"
      
      【你看着她的眼睛逐渐亮起来】
      
      "所以我们需要一个变量来'记住'当前的最大值，
      然后遍历数组，不断更新这个值。"
      
      雪梨："啊！我明白了！是这样的吗？"
      
      【她开始在键盘上敲击代码】
      
      "就是这个思路！你试试看。"
      
    character_development:
      xiaobai_affinity: 33
      xiaobai_growth: +15
      teaching_approach: "启发式"
      breakthrough_moment: true
      
    transitions:
      next: "development_xiaobai_004"
      
  development_xiaobai_004:
    type: "narrative"
    category: "development"
    title: "成长的喜悦"
    scene: "图书馆自习区"
    
    content: |
      【几分钟后】
      
      "学长！我写出来了！而且运行成功了！"
      雪梨兴奋地小声欢呼。
      
      【她转向你，眼中满含激动】
      
      "我终于明白了！原来编程不是记住代码，
      而是要理解问题的本质！"
      
      看到她如此开心，你也感到很欣慰。
      
      雪梨："学长，你真的是最好的老师！
      谢谢你这么耐心地教我！"
      
      【她突然有些害羞】
      
      "那个...明天我想请你喝奶茶，
      作为今天帮助我的谢礼，可以吗？"
      
      她的脸微微泛红，声音比平时更加轻柔。
      
    character_development:
      xiaobai_affinity: 40
      relationship_milestone: "第一次主动约请"
      emotional_connection: "感激转化为好感"
      
    dialogue_options:
      option_a:
        text: "当然可以，不过不用这么客气"
        xiaobai_affinity: "+5"
        humility: "+3"
        
      option_b:
        text: "好啊，我很期待"
        xiaobai_affinity: "+8"
        enthusiasm: "+3"
        
      option_c:
        text: "能帮到你就是最好的回报了"
        xiaobai_affinity: "+6"
        selflessness: "+5"
        
    transitions:
      next: "development_xiaobai_005"
      
  # 危机阶段
  crisis_xiaobai_001:
    type: "narrative"
    category: "crisis"
    title: "考试焦虑"
    scene: "图书馆自习区"
    
    content: |
      【场景：期中考试前一周，图书馆自习区】
      
      最近雪梨显得很焦虑。
      
      期中考试即将到来，而程序设计课的考试以难度大著称。
      虽然在你的帮助下她进步很大，
      但面对考试，她还是很没自信。
      
      【她坐在座位上，面前摊着一堆复习资料】
      
      "学长...我好害怕考试啊。"
      她的声音有些颤抖。
      
      "如果考不好，就会影响奖学金申请，
      我家里的经济条件不太好，很需要这个奖学金..."
      
      【她的眼中蓄满了泪水】
      
      看到平时开朗的雪梨如此沮丧，
      你的心中涌起了强烈的保护欲。
      
    character_development:
      xiaobai_affinity: 45
      vulnerability_revealed: "家庭经济困难"
      emotional_support_needed: true
      
    transitions:
      next: "crisis_xiaobai_002"
      
  crisis_xiaobai_002:
    type: "choice"
    category: "crisis"
    title: "如何支持"
    scene: "图书馆自习区"
    
    content: |
      看到雪梨的焦虑和担忧，你决定要帮助她。
      
      但是考试在即，该用什么方式帮助她呢？
      
    choices:
      choice_a:
        text: "制定详细的复习计划，陪她一起冲刺"
        effect:
          xiaobai_affinity: "+15"
          xiaobai_confidence: "+20"
          time_cost: "大量时间"
        next_frame: "crisis_xiaobai_003_intensive"
        
      choice_b:
        text: "整理重点知识笔记，提高复习效率"
        effect:
          xiaobai_affinity: "+12"
          xiaobai_confidence: "+15"
          time_cost: "适中时间"
        next_frame: "crisis_xiaobai_003_notes"
        
      choice_c:
        text: "给她心理支持和鼓励，缓解焦虑"
        effect:
          xiaobai_affinity: "+8"
          xiaobai_confidence: "+10"
          emotional_bond: "+15"
        next_frame: "crisis_xiaobai_003_support"
        
      choice_d:
        text: "建议她找老师或其他同学帮忙"
        effect:
          xiaobai_affinity: "-3"
          independence: "+5"
        next_frame: "crisis_xiaobai_003_others"
        
  crisis_xiaobai_003_intensive:
    type: "narrative"
    category: "crisis"
    title: "冲刺复习"
    scene: "图书馆 → 教室 → 宿舍"
    
    content: |
      【场景：接下来的一周，各种学习场所】
      
      你决定放下自己的事情，全力帮助雪梨准备考试。
      
      【制定了详细的时间表】
      
      早上8点到12点：基础知识复习
      下午2点到6点：编程练习
      晚上7点到10点：模拟考试
      
      【你陪着她严格执行计划】
      
      "这道题的思路是什么？"
      "递归的终止条件是什么？"
      "这个算法的时间复杂度如何分析？"
      
      【一遍遍地练习，一次次地讲解】
      
      虽然很累，但看到雪梨一天天进步，
      从最初的慌乱到逐渐的自信，你觉得一切都是值得的。
      
      【考试前夜】
      
      "学长，谢谢你...如果没有你，我真的不知道该怎么办。"
      雪梨的眼中满含着感激和另一种说不清的情感。
      
    character_development:
      xiaobai_affinity: 60
      xiaobai_confidence: 90
      deep_gratitude: true
      sacrifice_recognized: true
      
    transitions:
      next: "resolution_xiaobai_001"
      
  # 解决阶段
  resolution_xiaobai_001:
    type: "narrative"
    category: "resolution"
    title: "考试结果"
    scene: "教学楼走廊"
    
    content: |
      【场景：考试结束后，教学楼走廊】
      
      考试结束了。
      
      雪梨从考场走出来，脸上带着轻松的笑容。
      
      "学长！我觉得考得还不错！
      好多题目都是我们复习过的！"
      
      【她开心地跑向你】
      
      "最后那道算法题，我用了你教的那个方法，
      写得很顺利！"
      
      看到她重新找回的自信，你也松了一口气。
      
      【一周后，成绩公布】
      
      雪梨拿到了92分的高分，
      不仅保住了奖学金，还进入了班级前五名。
      
      "学长！我成功了！"
      她激动地给你发来消息。
      
    character_development:
      xiaobai_affinity: 75
      achievement_unlocked: "考试成功"
      confidence_restored: true
      
    transitions:
      next: "resolution_xiaobai_002"
      
  resolution_xiaobai_002:
    type: "dialogue"
    category: "resolution"
    title: "感谢的话语"
    scene: "校园咖啡厅"
    
    content: |
      【场景：校园咖啡厅，庆祝的下午茶】
      
      为了庆祝考试成功，雪梨请你来到校园里的咖啡厅。
      
      雪梨："学长，这是我的一点心意。"
      
      【她递给你一个精美的包装盒】
      
      打开一看，是一个手工制作的书签，
      上面写着一段代码——正是你教她的第一个程序。
      
      雪梨："我想...我想对你表达我的感谢。
      不仅仅是学习上的帮助，
      还有你对我的耐心、关心和信任。"
      
      【她的眼中闪闪发光】
      
      "在遇到你之前，我总觉得自己很笨，
      什么都学不会。
      但是你让我相信，只要努力，就一定能成功。"
      
      【她停顿了一下，似乎想说些什么】
      
      "学长...你对我来说，已经不只是老师那么简单了..."
      
    character_development:
      xiaobai_affinity: 85
      emotional_confession: "暗示特殊感情"
      handmade_gift: "用心准备的礼物"
      
    dialogue_options:
      option_a:
        text: "你对我来说也很特别"
        xiaobai_affinity: "+15"
        romance_flag: true
        
      option_b:
        text: "能帮到你我很开心"
        xiaobai_affinity: "+8"
        
      option_c:
        text: "你的进步是你自己努力的结果"
        xiaobai_affinity: "+10"
        humility: "+5"
        
    transitions:
      next: "resolution_xiaobai_003"
      
  # 结局准备
  pre_ending_xiaobai_001:
    type: "narrative"
    category: "resolution"
    title: "编程竞赛"
    scene: "计算机学院实验室"
    
    content: |
      【场景：学期末，计算机学院实验室】
      
      学校组织了一场编程竞赛，雪梨报名参加了。
      
      这是她第一次参加正式的编程比赛，
      虽然经过了充分的准备，但还是很紧张。
      
      【比赛当天】
      
      "学长...我有点紧张。"
      雪梨在比赛开始前找到你。
      
      "如果我做不出来题目怎么办？"
      
      【你看着她的眼睛】
      
      "还记得我们第一次见面时吗？
      那时候你连for循环都写不好，
      现在你已经能参加编程竞赛了。"
      
      "相信自己，你已经成长了很多。"
      
      【比赛开始】
      
      通过透明玻璃，你看到雪梨专注地编程，
      那种认真的神情让你想起了第一次见面的场景。
      
    character_development:
      xiaobai_affinity: 95
      growth_milestone: "独立参加竞赛"
      support_role: "精神支柱"
      
    transitions:
      condition: "if affinity >= 100"
      success: "ending_xiaobai_true"
      failure: "ending_xiaobai_good"
      
  # 真结局触发条件检查
  affinity_check_xiaobai:
    type: "system"
    category: "resolution"
    
    conditions:
      true_ending:
        xiaobai_affinity: ">=100"
        teaching_moments: ">=8"
        crisis_helped: true
        emotional_support: true
        
      good_ending:
        xiaobai_affinity: ">=80"
        teaching_moments: ">=5"
        
      normal_ending:
        xiaobai_affinity: ">=60"
        
      friend_ending:
        xiaobai_affinity: "<60"
        
    transitions:
      true_ending: "ending_xiaobai_true"
      good_ending: "ending_xiaobai_good"
      normal_ending: "ending_xiaobai_normal"
      friend_ending: "ending_xiaobai_friend"
